# Generated by Django 5.1.3 on 2024-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                (
                    "region",
                    models.CharField(
                        choices=[("kg", "kg"), ("kz", "kz"), ("uz", "uz")], max_length=2
                    ),
                ),
                ("user_id", models.CharField(max_length=123)),
                ("username", models.CharField(max_length=123)),
                ("good_id", models.CharField(max_length=123)),
                ("order_id", models.CharField(max_length=123)),
                ("link", models.CharField(max_length=123)),
                ("status", models.CharField(max_length=123)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recvisity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("kg", "kg"), ("kz", "kz"), ("uz", "uz")],
                        max_length=2,
                        verbose_name="Регион",
                    ),
                ),
                ("title", models.CharField(max_length=123, verbose_name="Название")),
                (
                    "number",
                    models.CharField(max_length=123, verbose_name="Карта или номер"),
                ),
                (
                    "account",
                    models.CharField(
                        max_length=123, verbose_name="Чья карта, чтобы мы знали"
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизит",
                "verbose_name_plural": "Реквизиты",
            },
        ),
        migrations.CreateModel(
            name="SingleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123, verbose_name="Название")),
                ("procent", models.FloatField(verbose_name="Процент")),
                ("mail", models.EmailField(max_length=254, verbose_name="Почта")),
                ("canal", models.CharField(max_length=123, verbose_name="Канал тг")),
                (
                    "podderjka",
                    models.CharField(
                        max_length=123, verbose_name="Ссылка на поддержку"
                    ),
                ),
            ],
            options={
                "verbose_name": "Общие данные",
                "verbose_name_plural": "Общие данные",
            },
        ),
    ]
