# Generated by Django 5.1.3 on 2024-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="link",
            field=models.TextField(),
        ),
    ]
